export const destinations = [
  {
    id: 1,
    type: 'mountain',
    name: "Everest",
    subtitle: "Peak XV",
    desc: "Standing as the highest point on Earth, the summit of Mount Everest represents the ultimate frontier of human endurance and the sublime power of the natural world.",
    heroImage: "https://images.unsplash.com/photo-1522163182402-834f871fd851?ixlib=rb-4.0.3&auto=format&fit=crop&w=2500&q=80",
    lat: 27.9881,
    lng: 86.9250,
    zoneTitle: "Extreme Altitude / Zone 8",
    elevationMeters: "8848.86 Meters",
    location: "Himalayan Range",
    introTitle: "The Roof of the World",
    introText: "Mount Everest is Earth's highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas. The China–Nepal border runs across its summit point. Its elevation of 8,848.86 m (29,031.7 ft) was most recently established in 2020 by the Chinese and Nepali authorities.",
    facts: [
      { id: 'f1', icon: 'Map', title: "Elevation", value: "8,848m", desc: "29,032 ft above sea level" },
      { id: 'f2', icon: 'ThermometerSnowflake', title: "Temperature", value: "-60°C", desc: "Can drop to -76°F in winter" },
      { id: 'f3', icon: 'Wind', title: "Wind Speed", value: "285 km", desc: "Hurricane-force winds" },
      { id: 'f4', icon: 'Users', title: "First Ascent", value: "1953", desc: "Hillary & Tenzing Norgay" },
    ],
    historySub: "Extreme Risks",
    historyTitle: "The Death Zone",
    historyText1: "Above 8,000 meters (26,000 ft), the air is so thin that the human body cannot survive for long. Oxygen levels are roughly a third of those at sea level. Climbers face extreme risks including altitude sickness, frostbite, and unpredictable avalanches.",
    historyText2: "Despite the danger, thousands have attempted the summit, drawn by the ultimate test of human endurance and the allure of standing at the highest point on Earth.",
    historyImage: "https://images.unsplash.com/photo-1544198365-f5d60b6d8190?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    historyCalloutLabel: "Khumbu Icefall",
    historyCalloutValue: "5,486 m",
  },
  {
    id: 2,
    type: 'mountain',
    name: "K2",
    subtitle: "Savage Mountain",
    desc: "The second-highest mountain on Earth, notorious for its extreme difficulty and volatile, unpredictable weather conditions.",
    heroImage: "https://images.unsplash.com/photo-1528892677828-8862216f3665?ixlib=rb-4.0.3&auto=format&fit=crop&w=2500&q=80",
    lat: 35.8809,
    lng: 76.5151,
    zoneTitle: "Karakoram Range / Zone 8",
    elevationMeters: "8611 Meters",
    location: "Karakoram Range",
    introTitle: "The Mountaineer's Mountain",
    introText: "K2, at 8,611 metres above sea level, is the second-highest mountain on Earth. It lies in the Karakoram range, spanning the Gilgit-Baltistan region of Pakistan and the Xinjiang region of China. It is notoriously known as the Savage Mountain.",
    facts: [
      { id: 'f1', icon: 'Map', title: "Elevation", value: "8,611m", desc: "28,251 ft above sea level" },
      { id: 'f2', icon: 'ThermometerSnowflake', title: "Temperature", value: "-50°C", desc: "Bitterly cold in winter" },
      { id: 'f3', icon: 'Wind', title: "Wind Speed", value: "200 km", desc: "Fierce Karakoram storms" },
      { id: 'f4', icon: 'Users', title: "First Ascent", value: "1954", desc: "Lacedelli & Compagnoni" },
    ],
    historySub: "The Final Push",
    historyTitle: "The Bottleneck",
    historyText1: "The most dangerous section of the climb is the Bottleneck, a narrow couloir overhung by seracs from an ice field east of the summit. Seracs can break off at any time, sweeping away climbers below.",
    historyText2: "K2 has the second-highest fatality rate among the eight-thousanders. With about one person dying on the mountain for every four who reach the summit, it is considered much harder to climb than Everest.",
    historyImage: "https://images.unsplash.com/photo-1483728642387-6c3ba6c66c75?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    historyCalloutLabel: "Base Camp",
    historyCalloutValue: "5,117 m",
  },
  {
    id: 3,
    type: 'mountain',
    name: "Mt. Fuji",
    subtitle: "Sacred Peak",
    desc: "Japan's most iconic peak, an active stratovolcano representing breathtaking beauty and deep spiritual significance.",
    heroImage: "https://images.unsplash.com/photo-1498855926480-d98e83099315?ixlib=rb-4.0.3&auto=format&fit=crop&w=2500&q=80",
    lat: 35.3606,
    lng: 138.7274,
    zoneTitle: "Honshu / Stratovolcano",
    elevationMeters: "3776 Meters",
    location: "Honshu, Japan",
    introTitle: "Symbol of Japan",
    introText: "Mount Fuji is the highest mountain in Japan, standing 3,776.24 m (12,389.2 ft). It is the second-highest volcano located on an island in Asia. Its exceptionally symmetrical cone is snow-capped for about five months a year.",
    facts: [
      { id: 'f1', icon: 'Map', title: "Elevation", value: "3,776m", desc: "12,389 ft above sea level" },
      { id: 'f2', icon: 'ThermometerSnowflake', title: "Temperature", value: "-20°C", desc: "Average winter temperature" },
      { id: 'f3', icon: 'Wind', title: "Wind Speed", value: "100 km", desc: "Variable summit winds" },
      { id: 'f4', icon: 'Users', title: "First Ascent", value: "663", desc: "Anonymous monk" },
    ],
    historySub: "Cultural Icon",
    historyTitle: "A Sacred Journey",
    historyText1: "Mount Fuji is a well-known symbol of Japan and is frequently depicted in art and photographs. It has been considered a sacred mountain for centuries, inspiring artists, poets, and pilgrims.",
    historyText2: "Historically, it was considered so sacred that women were forbidden from climbing it until the Meiji Era (late 19th century). Today, it attracts hundreds of thousands of climbers every year.",
    historyImage: "https://images.unsplash.com/photo-1542051812871-7575058e4bb9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    historyCalloutLabel: "Yoshida Trail",
    historyCalloutValue: "2,300 m",
  },
  {
    id: 4,
    type: 'forest',
    name: "Sundarbans",
    subtitle: "Mangrove Forest",
    desc: "The largest mangrove forest in the world, home to the majestic Royal Bengal Tiger and a complex network of tidal waterways.",
    heroImage: "https://upload.wikimedia.org/wikipedia/commons/0/05/Dense_Mangrove_Forest_of_the_Sundarban_Tiger_Reserve_during_High_Tide%2C_West_Bengal%2C_India_03.jpg",
    lat: 21.9497,
    lng: 89.1833,
    zoneTitle: "Delta Region / Sea Level",
    elevationMeters: "0-3 Meters",
    location: "Khulna, Bangladesh",
    introTitle: "The Amazon of the East",
    introText: "The Sundarbans is a vast forest in the coastal region of the Bay of Bengal, considered one of the natural wonders of the world. It is known for its wide range of fauna, including the Bengal tiger, water fowl, crocodile and snakes.",
    facts: [
      { id: 'f1', icon: 'Map', title: "Area", value: "10,000 km²", desc: "Across Bangladesh & India" },
      { id: 'f2', icon: 'ThermometerSnowflake', title: "Climate", value: "Tropical", desc: "Humid and warm" },
      { id: 'f3', icon: 'Wind', title: "Tides", value: "Diurnal", desc: "Complex tidal network" },
      { id: 'f4', icon: 'Users', title: "Wildlife", value: "Tigers", desc: "Home of Bengal Tigers" },
    ],
    historySub: "Biodiversity",
    historyTitle: "A Fragile Ecosystem",
    historyText1: "The interconnected network of waterways makes almost every corner of the forest accessible by boat. The forest provides a unique ecosystem and a rich wildlife habitat.",
    historyText2: "It acts as a vital protective barrier for the inhabitants in and around Khulna and Mongla against the floods that result from the cyclones.",
    historyImage: "https://images.unsplash.com/photo-1557401622-6b99decd5e81?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    historyCalloutLabel: "Heritage Site",
    historyCalloutValue: "UNESCO",
  },
  {
    id: 5,
    type: 'mountain',
    name: "Sajek Valley",
    subtitle: "Queen of Hills",
    desc: "Emerging from the mist, Sajek Valley is known for its lush green hills, serene environment, and the sea of clouds that blanket the valleys.",
    heroImage: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Sunrise_at_Sajek_Valley.jpg",
    lat: 23.3833,
    lng: 92.2833,
    zoneTitle: "Chittagong Hill Tracts",
    elevationMeters: "548 Meters",
    location: "Rangamati, Bangladesh",
    introTitle: "The Sea of Clouds",
    introText: "Sajek Valley is an emerging tourist spot in Bangladesh situated among the hills of the Kasalong range of mountains in Sajek union, Baghaichhari Upazila in Rangamati District. It is known as the Queen of Hills & Roof of Rangamati.",
    facts: [
      { id: 'f1', icon: 'Map', title: "Elevation", value: "548m", desc: "1,800 ft above sea level" },
      { id: 'f2', icon: 'ThermometerSnowflake', title: "Weather", value: "15-25°C", desc: "Cool and pleasant" },
      { id: 'f3', icon: 'Wind', title: "Atmosphere", value: "Misty", desc: "Sea of clouds" },
      { id: 'f4', icon: 'Users', title: "Culture", value: "Indigenous", desc: "Lushei, Tripura, Chakma" },
    ],
    historySub: "Hill Tracts",
    historyTitle: "A Serene Escape",
    historyText1: "The name of Sajek Valley came from the Sajek River that originates from Karnafuli river. The valley is surrounded by mountains, dense forest, and grassland hill tracks.",
    historyText2: "Many women of the ethnic groups in Sajek are involved in making handloom cloth. The peaceful coexistence of nature and indigenous culture makes it a truly unique destination.",
    historyImage: "https://images.unsplash.com/photo-1589311685375-74943f25c7e1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    historyCalloutLabel: "Ruilui Para",
    historyCalloutValue: "Village",
  },
  {
    id: 6,
    type: 'beach',
    name: "Cox's Bazar",
    subtitle: "Longest Sea Beach",
    desc: "The unbroken golden sand beach stretches for 120 kilometers, making it the longest natural sea beach in the world.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2500&q=80",
    lat: 21.4272,
    lng: 92.0058,
    zoneTitle: "Bay of Bengal / Coastal",
    elevationMeters: "3 Meters",
    location: "Chittagong, Bangladesh",
    introTitle: "The Golden Coast",
    introText: "Cox's Bazar is a city, fishing port, tourism centre, and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach, and it is a popular tourist destination.",
    facts: [
      { id: 'f1', icon: 'Map', title: "Length", value: "120 km", desc: "Longest unbroken beach" },
      { id: 'f2', icon: 'ThermometerSnowflake', title: "Climate", value: "Tropical", desc: "Warm year-round" },
      { id: 'f3', icon: 'Wind', title: "Waves", value: "Gentle", desc: "Perfect for surfing" },
      { id: 'f4', icon: 'Users', title: "Tourism", value: "Millions", desc: "Most visited in BD" },
    ],
    historySub: "Coastal Wonder",
    historyTitle: "Endless Horizon",
    historyText1: "The beach in Cox's Bazar is an unbroken 120 km (75 mi) sandy sea beach with a gentle slope. It is the top tourist destination of Bangladesh.",
    historyText2: "From the spectacular sunsets over the Bay of Bengal to the vibrant local culture and seafood, it offers an unforgettable coastal experience.",
    historyImage: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    historyCalloutLabel: "Marine Drive",
    historyCalloutValue: "80 km",
  }
];
